const keywords = [
  "Mobile Repair Kukatpally",
  "KPHB Phone Repair",
  "Hyderabad Mobile Repair",
  "Kukatpally Phone Service",
  "Smartphone Repair KPHB",
  "Kukatpally Device Repair",
  "Cell Phone Repair Hyderabad",
  "Mobile Screen Replacement Kukatpally",
  "Battery Replacement KPHB",
  "Water Damage Repair Hyderabad",
  "iPhone Repair Kukatpally",
  "Samsung Mobile Repair Kukatpally",
  "Vivo Mobile Repair KPHB",
  "Oppo Phone Repair Hyderabad",
  "Xiaomi Repair Kukatpally",
  "Redmi Mobile Fix KPHB",
  "OnePlus Repair Hyderabad",
  "Google Pixel Repair Kukatpally",
  "Top Mobile Repair Shop KPHB",
  "Affordable Phone Fix Hyderabad",
  "Same-Day Mobile Repair Kukatpally",
  "Authorized Mobile Repair Center",
  "Quick Mobile Service KPHB",
  "Mobile Repair Warranty Kukatpally",
  "Expert Phone Repair Hyderabad",
  "Mobile repair Kukatpally (KPHB)",
  "Mobile repair Hyderabad",
  "Samsung repair Kukatpally (KPHB)",
  "Vivo repair Kukatpally (KPHB)",
  "Oppo repair Kukatpally (KPHB)",
  "Mi repair Kukatpally (KPHB)",
  "Redmi repair Kukatpally (KPHB)",
  "iPhone repair Kukatpally (KPHB)",
  "Screen repair Kukatpally (KPHB)",
  "Battery replacement Kukatpally (KPHB)",
  "Water damage repair Kukatpally (KPHB)",
  "Software repair Kukatpally (KPHB)",
  "Hardware repair Kukatpally (KPHB)",
  "Mobile repair near me",
  "Mobile repair shop Kukatpally (KPHB)",
  "Mobile repair services Kukatpally (KPHB)",
  "Best mobile repair shop Kukatpally (KPHB)",
  "Cheap mobile repair Kukatpally (KPHB)",
  "Same-day mobile repair Kukatpally (KPHB)",
  "Mobile repair estimate Kukatpally (KPHB)",
  "Mobile repair shop Kukatpally",
  "Mobile repair shop Hyderabad",
  "Samsung mobile repair Kukatpally",
  "Vivo mobile repair Kukatpally",
  "Oppo mobile repair Kukatpally",
  "Mi mobile repair Kukatpally",
  "Redmi mobile repair Kukatpally",
  "iPhone mobile repair Kukatpally",
  "Mobile screen repair Kukatpally",
  "Mobile battery replacement Kukatpally",
  "Mobile water damage repair Kukatpally",
  "Mobile software repair Kukatpally",
  "Mobile hardware repair Kukatpally",
  "Mobile repair warranty Kukatpally",
  "Same-day mobile repair Kukatpally",
  "Mobile repair while you wait Kukatpally",
  "Best mobile repair shop Kukatpally",
  "Top mobile repair shop Kukatpally",
  "Mobile repair shop Kukatpally Samsung Galaxy S22",
  "Mobile repair shop Kukatpally Vivo V25 Pro",
  "Mobile repair shop Kukatpally Oppo Reno 8 Pro",
  "Mobile repair shop Kukatpally Mi 11 Ultra",
  "Mobile repair shop Kukatpally Redmi Note 11 Pro",
  "Mobile repair shop Kukatpally iPhone 13 Pro",
  "Mobile screen repair Kukatpally Samsung Galaxy S22 Ultra",
  "Mobile battery replacement Kukatpally Vivo V23 Pro",
  "Mobile water damage repair Kukatpally Oppo Reno 7 Pro",
  "Mobile software repair Kukatpally Mi 11i HyperCharge",
  "Mobile hardware repair Kukatpally Redmi Note 11 Pro+ 5G",
  "Mobile repair warranty Kukatpally iPhone 13 Pro Max",
  "Same-day mobile repair Kukatpally Samsung Galaxy Z Fold 3",
  "Mobile repair while you wait Kukatpally Vivo V23e",
  "Best mobile repair shop Kukatpally Samsung Galaxy A53 5G",
  "Top mobile repair shop Kukatpally Vivo Y75 5G",
  "Trusted mobile repair shop Kukatpally Oppo A77s",
  "Mobile repair near me Kukatpally",
  "Best mobile repair shop in Kukatpally",
  "Top mobile repair shop in Kukatpally",
  "Trusted mobile repair shop in Kukatpally",
  "Affordable mobile repair shop in Kukatpally",
  "Quick mobile repair shop in Kukatpally",
  "Expert mobile repair shop in Kukatpally",
  "Express mobile repair shop in Kukatpally",
  "Walk-in mobile repair shop in Kukatpally",
  "Authorized mobile repair shop in Kukatpally",
  "Samsung mobile repair specialist in Kukatpally",
  "Vivo mobile repair specialist in Kukatpally",
  "Oppo mobile repair specialist in Kukatpally",
  "Mi mobile repair specialist in Kukatpally",
  "Redmi mobile repair specialist in Kukatpally",
  "iPhone mobile repair specialist in Kukatpally",
  "Samsung mobile repair Kukatpally KPHB",
  "Vivo mobile repair Kukatpally KPHB",
  "Oppo mobile repair Kukatpally KPHB",
  "Mi mobile repair Kukatpally KPHB",
  "Redmi mobile repair Kukatpally KPHB",
  "iPhone mobile repair Kukatpally KPHB",
  "samsung mobile service center near me",
  "samsung mobile service center hyderabad",
  "samsung service center near me",
  "samsung858",
  "samsung mobile service center near me hyderabad",
  "samsung mobile service center",
  "samsung store near me",
  "samsung service center",
  "samsung service centre near me",
  "samsung service center hyderabad",
  "samsung repair310",
  "samsung phone service center near me",
  "mobile repair shop near me",
  "Mobile repair Kukatpally",
  "KPHB Mobile repair",
  "Hyderabad Mobile repair",
  "Kukatpally Phone repair",
  "Hyderabad Mobile service",
  "Cell Phone repair Kukatpally",
  "Kukatpally Mobile screen repair",
  "Mobile battery replacement Kukatpally",
  "Water damage repair Hyderabad",
  "Mobile software repair Kukatpally",
  "Mobile hardware repair Hyderabad",
  "iPhone repair Kukatpally",
  "Samsung Mobile repair Kukatpally",
  "Vivo Mobile repair Kukatpally",
  "Oppo Mobile repair Kukatpally",
  "Xiaomi Mobile repair Kukatpally",
  "Redmi Mobile repair Kukatpally",
  "OnePlus Mobile repair Hyderabad",
  "Google Pixel Phone repair KPHB",
  "Best Mobile repair shop Kukatpally",
  "Top Mobile repair services Kukatpally",
  "Affordable Mobile repair Hyderabad",
  "Same-day Mobile repair Kukatpally",
  "Mobile repair warranty Kukatpally",
  "Authorized Mobile repair center Kukatpally",
  "Mobile Phone repair service Kukatpally",
  "Cell Phone screen repair Hyderabad",
  "Cracked Phone screen repair KPHB",
  "Kukatpally Gadget repair shop",
  "Tablet repair services Kukatpally",
  "Mobile Phone technician Kukatpally",
  "Fix Broken Phone Kukatpally",
  "Phone screen replacement KPHB",
  "Waterproof Phone repair Hyderabad",
  "Kukatpally Mobile Phone hospital",
  "Quick Mobile repair service Kukatpally",
  "Mobile Phone glass repair Hyderabad",
  "Mobile repair shop for all brands",
  "Expert Mobile repair technicians",
  "Kukatpally Phone unlocking service",
  "Professional Mobile device repair",
  "Smartphone repair store Hyderabad",
  "Best Mobile repair center KPHB",
  "Affordable Phone fix Kukatpally",
  "Mobile repair and accessories",
  "Fast Phone diagnosis Hyderabad",
  "24/7 Mobile repair shop Kukatpally",
  "Emergency Phone repair services",
  "Authorized Phone service center",
  "Quality Mobile repair solutions",
  "Top-rated Mobile repair specialist",
  "Best Mobile repair service near me",
  "Mobile screen replacement Hyderabad",
  "Mobile charging port repair KPHB",
  "Data recovery for Mobile phones",
  "Battery replacement service Kukatpally",
  "Cell Phone accessories Hyderabad",
  "Screen protector installation KPHB",
  "Mobile Phone camera repair Kukatpally",
  "Professional Mobile chip repair",
  "Kukatpally Mobile device support",
  "Mobile Phone speaker repair",
  "Unlock your Phone KPHB",
  "Reliable Mobile repair experts",
  "Mobile repair parts and service",
  "Best Phone repair warranty",
  "Fix My Phone in Kukatpally",
  "Quick and affordable Phone fixes",
  "Certified Mobile repair center",
  "Mobile Phone technician in KPHB",
  "Tablet screen repair Hyderabad",
  "Top-notch Phone screen replacement",
  "Affordable Mobile repair Kukatpally",
  "Skilled Mobile repair specialists",
  "Mobile Phone repair and service",
  "Mobile repair store near me",
  "Kukatpally Mobile device repair",
  "Broken Phone screen repair KPHB",
  "Reliable Phone repair technicians",
  "Expert Mobile Phone solutions",
  "Fast Mobile repair services",
  "Mobile Phone screen fix Hyderabad",
  "Fix Broken Smartphone Kukatpally",
  "Water damage Phone repair KPHB",
  "Kukatpally Mobile Phone repair shop",
  "Quick and affordable Phone repairs",
  "Mobile repair shop for all models",
  "Professional Phone screen repair",
  "Skilled Mobile repair specialists",
  "Best Mobile repair shop in KPHB",
  "Mobile Phone technician near me",
  "Mobile Phone repair and accessories",
  "Mobile device screen repair Hyderabad",
  "Authorized Phone service center Kukatpally",
  "Best Mobile repair center near me",
  "Emergency Mobile repair services",
  "Mobile Phone speaker repair KPHB",
  "Quick and affordable Mobile fixes",
  "Mobile Phone repair warranty",
  "Mobile Phone camera repair Hyderabad",
  "samsung services centre, ",
];

export default keywords;
